name: terraform apply
on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
    types:
      - closed

defaults:
  run:
    working-directory: terraform/envs/prd

jobs:
  tf_apply:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: authenticate to google cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 1200s
      
      - name: checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      - name: terraform fmt
        id: fmt
        run: terraform fmt -check
      
      - name: terraform init
        id: init
        run: terraform init
      
      - name: terraform apply
        id: apply
        env: 
          TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
        run: terraform apply -no-color